server:
  port: 8010

spring:
  application:
    # 服务逻辑名称
    name: system-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: book-center-rpc
          uri: lb://system-cloud-book
          predicates:
            - Path=/book/**
            - Method=GET
          filters:
            # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
            # 限流配置
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3 # 每秒允许处理的请求数量
                redis-rate-limiter.burstCapacity: 5 # 每秒最大处理的请求数量
                key-resolver: "#{@ipKeyResolver}" # 限流策略，对应策略的Bean


        - id: homepage-rpc
          uri: lb://system-cloud-homepage
          predicates:
            - Path=/index/**
          filters:
            # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
            # 限流配置
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@ipKeyResolver}"

        - id: account-center-rpc
          uri: lb://system-cloud-account
          predicates:
            - Path=/account/**
          filters:
            # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
            # 限流配置
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@ipKeyResolver}"
  #---- redis配置  ----#
  redis:
    database: 0
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 30
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 10
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          max-wait: -1ms
          min-idle: 0
        shutdown-timeout: 100ms
#eureka:
#  instance:
#    # 注册服务的IP，而不是逻辑名称
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:1001/eureka/
#    register-with-eureka: true
#    fetch-registry: true

hystrix:
  threadpool:
    default:
      coreSize: 20 #并发执行的最大线程数，默认10
      maxQueueSize: 1000 #BlockingQueue的最大队列数，默认值-1
      queueSizeRejectionThreshold: 400


