version: '3.9'

services:
  system-cloud-gateway:
    build: system-cloud-gateway
    image: system-cloud-gateway:${NOVEL_CLOUD_VERSION}
    container_name: system-cloud-gateway
    restart: "always"
    environment:
      - JAR_VERSION=${NOVEL_CLOUD_VERSION}
      - NACOS_ADDR=${NACOS_ADDRESS}:8848
    ports:
      - "8010:8010"
    networks:
      - api-center-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:8888 | grep -q 'HTTP/1.1 404 Not Found'",
        ]
      interval: 10s
      timeout: 2s
      retries: 120

  system-cloud-book:
    build: system-cloud-book
    image: system-cloud-book:${NOVEL_CLOUD_VERSION}
    container_name: system-cloud-book
    restart: "always"
    environment:
      - JAR_VERSION=${NOVEL_CLOUD_VERSION}
      - NACOS_ADDR=${NACOS_ADDRESS}:8848
    ports:
      - "8001:8001"
    networks:
      - api-center-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:9001 | grep -q 'HTTP/1.1 404 Not Found'",
        ]
      interval: 10s
      timeout: 2s
      retries: 120
  
  system-cloud-homepage:
    build: system-cloud-homepage
    image: system-cloud-homepage:${NOVEL_CLOUD_VERSION}
    container_name: system-cloud-homepage
    restart: "always"
    environment:
      - JAR_VERSION=${NOVEL_CLOUD_VERSION}
      - NACOS_ADDR=${NACOS_ADDRESS}:8848
    ports:
      - "9030:9030"
    networks:
      - api-center-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:9030 | grep -q 'HTTP/1.1 404 Not Found'",
        ]
      interval: 10s
      timeout: 2s
      retries: 120

  system-cloud-account:
    build: system-cloud-account
    image: system-cloud-account:${NOVEL_CLOUD_VERSION}
    container_name: system-cloud-account
    restart: "always"
    environment:
      - JAR_VERSION=${NOVEL_CLOUD_VERSION}
      - NACOS_ADDR=${NACOS_ADDRESS}:8848
    ports:
      - "8003:8003"
    networks:
      - api-center-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:9020 | grep -q 'HTTP/1.1 404 Not Found'",
        ]
      interval: 10s
      timeout: 2s
      retries: 120

networks:
  api-center-net:
    driver: bridge